"""Read-only scan of the frozen World Anvil corpus -> docs/corpus-report.md.

Usage: python scripts/corpus_report.py [WA_DIR]
"""
import collections
import glob
import json
import os
import re
import sys

from wa_common import WA_DIR, KIND_OF_TYPE, KNOWN_TAGS

wa = sys.argv[1] if len(sys.argv) > 1 else WA_DIR
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = os.path.join(root, 'docs', 'corpus-report.md')

arts = {}
bodies = {}
for f in sorted(glob.glob(os.path.join(wa, 'articles', '*.json'))):
    d = json.load(open(f, encoding='utf-8'))
    arts[d['slug']] = d
    b = f[:-5] + '.bbcode'
    bodies[d['slug']] = open(b, 'rb').read() if os.path.exists(b) else None

n = len(arts)
L = []
w = L.append
w('# Corpus report: World Anvil export\n')
w(f'Source: `{wa}\\articles` (frozen). {n} `.json` sidecars, '
  f'{sum(1 for b in bodies.values() if b is not None)} `.bbcode` bodies. Generated by `scripts/corpus_report.py`.\n')

# --- keys
keys = collections.Counter(k for d in arts.values() for k in d)
w('## Sidecar keys\n')
w('| Key | Articles | |')
w('|---|---:|---|')
for k, c in keys.most_common():
    w(f'| `{k}` | {c} | {"universal" if c == n else "partial"} |')
w('')

# --- types
types = collections.Counter(d['type'] for d in arts.values())
w('## `type` values and proposed `kind`\n')
w('| type | Articles | kind (site folder) |')
w('|---|---:|---|')
for t, c in types.most_common():
    w(f'| {t} | {c} | `{KIND_OF_TYPE.get(t, "??")}` |')
kinds = collections.Counter(KIND_OF_TYPE.get(d['type'], '??') for d in arts.values())
w('\nResulting kinds: ' + ', '.join(f'`{k}` {c}' for k, c in kinds.most_common()) + '\n')

# --- fields per type
w('## `fields` by type\n')
w('Keys on at least 80% of that type are "core"; keys on one article only are "one-off".\n')
by_type = collections.defaultdict(list)
for d in arts.values():
    by_type[d['type']].append(d)
for t, _ in types.most_common():
    ds = by_type[t]
    fc = collections.Counter(k for d in ds for k in (d.get('fields') or {}))
    if not fc:
        w(f'- **{t}** ({len(ds)}): no fields')
        continue
    core = [k for k, c in fc.most_common() if c >= 0.8 * len(ds)]
    mid = [k for k, c in fc.most_common() if 1 < c < 0.8 * len(ds)]
    one = [k for k, c in fc.most_common() if c == 1 and len(ds) > 1]
    w(f'- **{t}** ({len(ds)}, {len(fc)} keys): core `{", ".join(core) or "-"}`'
      + (f'; some `{", ".join(mid)}`' if mid else '')
      + (f'; one-off `{", ".join(one)}`' if one else ''))
vt = collections.Counter(type(v).__name__ for d in arts.values() for v in (d.get('fields') or {}).values())
w(f'\nAll field values are of type: {dict(vt)}.\n')

# --- outliers
w('## Outliers\n')
w('- `note`: ' + '; '.join(f'`{s}`: {d["note"]}' for s, d in arts.items() if 'note' in d))
w(f'- `image_card`: {sum("image_card" in d for d in arts.values())} articles (ally cards).')
w(f'- `wa_uuid` null: {sum(not d.get("wa_uuid") for d in arts.values())}.')
uuid = [s for s, d in arts.items() if re.fullmatch(r'[0-9a-f-]{36}', d.get('wa_slug') or '')]
w(f'- UUID-string live slugs ({len(uuid)}): ' + ', '.join(f'`{s}`' for s in uuid))
mc = [s for s, d in arts.items() if 'militaryconflict' in (d.get('wa_slug') or '').lower()]
w(f'- `militaryConflict` slugs ({len(mc)}): sidecar `wa_slug` is lowercased; `slugtable.json` has the live camelCase.')
empty_ex = [s for s, d in arts.items() if not (d.get('excerpt') or '').strip()]
empty_tags = [s for s, d in arts.items() if not d.get('tags')]
no_src = [s for s, d in arts.items() if not d.get('sources')]
w(f'- Empty excerpt: {len(empty_ex)}' + (f' ({", ".join(empty_ex)})' if empty_ex else ''))
w(f'- Empty tags: {len(empty_tags)}' + (f' ({", ".join(empty_tags)})' if empty_tags else ''))
w(f'- Empty sources: {len(no_src)}' + (f' ({", ".join(no_src)})' if no_src else ''))
missing = [s for s, b in bodies.items() if b is None]
w(f'- Missing `.bbcode` body: {len(missing)}' + (f' ({", ".join(missing)})' if missing else ''))

# --- bbcode
tags = collections.Counter()
bad_utf8, mojibake = [], []
for s, raw in bodies.items():
    if raw is None:
        continue
    try:
        t = raw.decode('utf-8')
    except UnicodeDecodeError:
        bad_utf8.append(s)
        continue
    if re.search('Ã.|Â.|â€', t):
        mojibake.append(s)
    tags.update(m.lower() for m in re.findall(r'\[/?([a-zA-Z0-9]+)(?:=[^\]]*)?\]', t))
unknown = {k: c for k, c in tags.items() if k not in KNOWN_TAGS}
w(f'- Not valid UTF-8: {len(bad_utf8)}' + (f' ({", ".join(bad_utf8)})' if bad_utf8 else ''))
w(f'- Mojibake sequences (Ã, Â, â€): {len(mojibake)}' + (f' ({", ".join(mojibake)})' if mojibake else ''))
w(f'- Unknown BBCode tags: {unknown or "none"}\n')

w('## BBCode tags used\n')
w(', '.join(f'`{k}` {c}' for k, c in tags.most_common()) + '\n')

links = collections.Counter()
for raw in bodies.values():
    if raw:
        for h in re.findall(r'\[url=([^\]]*)\]', raw.decode('utf-8', 'replace')):
            links['article' if '/a/' in h else 'map' if '/map/' in h else 'other'] += 1
w(f'Links: {dict(links)}.\n')

os.makedirs(os.path.dirname(out), exist_ok=True)
open(out, 'w', encoding='utf-8', newline='\n').write('\n'.join(L))
print(f'wrote {out}')
